# Generated by Django 3.2.4 on 2021-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
