# Generated by Django 3.2.4 on 2021-08-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'foundation'), (2, 'non-governmental organisation'), (3, 'local collection')], default=1)),
                ('categories', models.ManyToManyField(to='donating.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=256)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=1024)),
                ('categories', models.ManyToManyField(to='donating.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donating.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
